### ISSUE TITLE
web添加查看所有已上线设备列表点击后自动跳转到登录设备终端界面

### ISSUE THREAD

**Issue by axlrose** [zhaojh329/rttys#1]
目前已实现了/list列出在线设备的json, 建议添加一个/listdev 区别/list，/listdev返回在线列表的html格式id号配描述的链接列表，用户点击其中一个设备链接就切到xxxx/rtty.html?did=xxxxxxx  ，实现免输入id功能,使登录更快捷

**Comment by zhaojh329** [comment]
done.
