### ISSUE TITLE
请问root为什么不能登录？

### ISSUE THREAD

**Issue by woniuxu** [zhaojh329/rttys#10]
如下：
NanoPi-NEO-Plus2 login: root
Login incorrect

root不能登录，其他账户可以登录，怎样才可以让root登录呢？

**Comment by zhaojh329** [comment]
这跟rtty没关系。

**Comment by woniuxu** [comment]
还没到输密码就报 Login incorrect，那请问是什么原因呢

**Comment by liyongjun123** [comment]
我也是，root账户登录设备不可以，其他账户就可以
![image](https://user-images.githubusercontent.com/33140023/63568051-91086400-c5a6-11e9-8649-87e258322b00.png)

**Comment by liangjiahuiLJH** [comment]
隐藏/etc/securetty文件或在文件中添加几行pts/0,pts/1,...,pts/n即可
