### ISSUE TITLE
访问设备网页时，如何同时访问到 websocket 数据

### ISSUE THREAD

**Issue by houzy** [zhaojh329/rttys#107]
### rtty
* arch: arm64
* os: debian 10
* version: 8.0.0

### rttys
* arch: x64
* os: ubuntu 18.04
* version: 8.0.1

## Description
通过 rttys 访问边缘侧设备网页时，指定 80 端口（127.0.0.1:80），可以成功打开其页面，但是这个页面比较特殊，其中一部分数据是通过 websocket协议获取的，端口是 11883，url 是 ws://x.x.x.x:11883/x，浏览器打开 debug 模式可以看到无法访问该端口，有什么办法能够让除了80这个端口外，websocket 协议也可以被正确访问到？

**Comment by zhaojh329** [comment]
收费定制开发。

**Comment by houzy** [comment]
> 收费定制开发。

就是说当前版本没有这个功能是吗？

**Comment by zhaojh329** [comment]
> > 收费定制开发。
> 
> 就是说当前版本没有这个功能是吗？

是的

**Comment by houzy** [comment]
好的，谢谢
