### ISSUE TITLE
v4.0.1版本打不开设备Web界面了，打开设备终端正常

### ISSUE THREAD

**Issue by houzy** [zhaojh329/rttys#108]
### rtty
* arch: arm64
* os: Debian 10
* version: v8.0.0

### rttys
* arch: amd64
* os: alpine
* version: v4.0.1

## Description
在 rttys 的界面上，点击某个设备的web图标，填写好设备的地址（如127.0.0.1:80），会在新标签页尝试打开改设备的web界面，但是该页面会一直卡出直到报超时错误。
rttys是用仓库提供的Dockerfile进行编译生成的，源码是v4.0.1版本。

打开设备终端的功能是正常的。

**Comment by zhaojh329** [comment]
我从 release 里面下载的，验证了，没问题.

**Comment by houzy** [comment]
好的，我再试一下直接使用release版本

**Comment by braincs** [comment]
rtty
arch: arm64
os: Linux
version: 8.1.0
rttys
arch: amd64
os: Ubuntu18.04
version: v4.1.1
也遇到上述情况，点击某个设备的web图标，填写好设备的地址（如127.0.0.1:80），跳转到http://ip:16501/?_=1699946814会卡主没有相应

打开设备终端的功能是正常的。

**Comment by braincs** [comment]
> rtty arch: arm64 os: Linux version: 8.1.0 rttys arch: amd64 os: Ubuntu18.04 version: v4.1.1 也遇到上述情况，点击某个设备的web图标，填写好设备的地址（如127.0.0.1:80），跳转到[http://ip:16501/?_=1699946814会卡主没有相应](http://ip:16501/?_=1699946814%E4%BC%9A%E5%8D%A1%E4%B8%BB%E6%B2%A1%E6%9C%89%E7%9B%B8%E5%BA%94)
> 
> 打开设备终端的功能是正常的。

已解决，http-proxy 端口没有解禁防火墙策略
