### ISSUE TITLE
能否提供docker版镜像

### ISSUE THREAD

**Issue by darcyg** [zhaojh329/rttys#11]
在hub.docker.com中
提供rttys的镜像服务，提供DockerFile

我在ubuntu 16.04下 用golang-go 1.6版无法go get 
我对go不熟，能否说明一下编译的环境和版本
详细操作流程。

下面是日志
================================
Generating a 2048 bit RSA private key
......................+++
......+++
writing new private key to 'output/ca.key'
-----
Created CA certificate in output/ca.crt
subject= 
    commonName                = An MQTT broker
    organizationName          = OwnTracks.org
    organizationalUnitName    = generate-CA
    emailAddress              = nobody@example.net
Warning: the CA key is not encrypted; store it safely!
--- Creating server key and signing request
Generating RSA private key, 2048 bit long modulus
....................................................................................................................................................................................................................................................................................................................................................................+++
................................................+++
e is 65537 (0x10001)
--- Creating and signing server certificate
Signature ok
subject=/CN=rttys/O=OwnTracks.org/OU=generate-CA/emailAddress=nobody@example.net
Getting CA Private Key
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../go/src/github.com/gorilla/websocket/client.go:9:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/darcy/go/src/context (from $GOPATH)
../../go/src/github.com/gorilla/websocket/client.go:16:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/darcy/go/src/net/http/httptrace (from $GOPATH)
rttys-linux-amd64/
rttys-linux-amd64/rttys.crt
rttys-linux-amd64/rttys.key
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../go/src/github.com/gorilla/websocket/client.go:9:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/darcy/go/src/context (from $GOPATH)
../../go/src/github.com/gorilla/websocket/client.go:16:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/darcy/go/src/net/http/httptrace (from $GOPATH)
rttys-linux-386/
rttys-linux-386/rttys.crt
rttys-linux-386/rttys.key
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../go/src/github.com/gorilla/websocket/client.go:9:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/darcy/go/src/context (from $GOPATH)
../../go/src/github.com/gorilla/websocket/client.go:16:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/darcy/go/src/net/http/httptrace (from $GOPATH)
  adding: rttys-windows-amd64/ (stored 0%)
  adding: rttys-windows-amd64/rttys.crt (deflated 32%)
  adding: rttys-windows-amd64/rttys.key (deflated 23%)
package context: unrecognized import path "context" (import path does not begin with hostname)
package net/http/httptrace: unrecognized import path "net/http/httptrace" (import path does not begin with hostname)
../../go/src/github.com/gorilla/websocket/client.go:9:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/darcy/go/src/context (from $GOPATH)
../../go/src/github.com/gorilla/websocket/client.go:16:2: cannot find package "net/http/httptrace" in any of:
	/usr/lib/go-1.6/src/net/http/httptrace (from $GOROOT)
	/home/darcy/go/src/net/http/httptrace (from $GOPATH)
  adding: rttys-windows-386/ (stored 0%)
  adding: rttys-windows-386/rttys.crt (deflated 32%)
  adding: rttys-windows-386/rttys.key (deflated 23%)

**Comment by zhaojh329** [comment]
可直接下载编译好的

**Comment by zhaojh329** [comment]
就是你的服务器的用户名和密码

**Comment by darcyg** [comment]
我做了一个docker的镜像，可以直接用，包括改密码，Dockerfile文件也提供了
https://hub.docker.com/r/darcyg/rttys

如果可以，希望可以编译一个alpine-3.8支持的rttys 
目前报错
standard_init_linux.go:190: exec user process caused "no such file or directory"
大约原因看这里
https://stackoverflow.com/questions/49079981/golang-app-in-docker-exec-user-process-caused-no-such-file-or-directory

go build前要加 CGO_ENABLED=0
