### ISSUE TITLE
api.go pattern ui/dist: no matching files found

### ISSUE THREAD

**Issue by RogerHardiman** [zhaojh329/rttys#123]
### rttys
* arch:  arm and amd64
* os:  Raspberry Pi OS (debian based) and Ubuntu22
* version:  git checkout of master

## Description
I'm new to Go so sorry if it is just lack of the build process.
I have checked out rttys on an Arm machine and an Intel 64 bit machine.
When I run build.sh linux arm    OR build.sh linux amd64
then both stop with the error
   api.go pattern ui/dist: no matching files found

A pointer on what this is and any suggestions to build from source would be great.

Go is version 1.18 on both machines.

Thanks
Roger
(open source developer)

**Comment by RogerHardiman** [comment]
Update. I think I need to build things in the UI folder.

**Comment by tr4nk0** [comment]
Hi, 

Did you solve the issue? Unfortunately, I'm new with go as well and i have the same problem.

Thanks,

**Comment by tr4nk0** [comment]
Okey solved.

When i built the ui I have an error related to the version of nvm installed. I updated that and everything worked fine.
