### ISSUE TITLE
不操作一段时间之后自动断开

### ISSUE THREAD

**Issue by sharp-shooter** [zhaojh329/rttys#14]
请问在浏览器中不操作一段时间之后，ssh自动断开了 这个怎么解决呢 有没有选项修改下无操作断开时间

**Comment by zhaojh329** [comment]
多长时间？是否能复现？

**Comment by sharp-shooter** [comment]
今天用chrome是这样  但是用360没事 一般无操作5分钟左右就会退出ssh，不知道为啥
