### ISSUE TITLE
Redirect to file of STDOUT not working

### ISSUE THREAD

**Issue by emanuelr93** [zhaojh329/rttys#15]
I have tried to start rttys with nohup and output is not redirected to the file /tmp/rttys.log

`nohup rttys -conf /data/conf/rttys.conf & > /tmp/rttys.log`

It is a logger problem?

**Comment by zhaojh329** [comment]
cat /var/log/rtty.log

**Comment by emanuelr93** [comment]
In docker container without root permission you cannot write in /var/log/.
We can customize log path or fix STDOUT output ?

**Comment by zhaojh329** [comment]
Will support this feature in the future.
