### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by sgaynetdinov** [zhaojh329/rttys#16]
Hi

1. git clone https://github.com/zhaojh329/rttys.git
1. cd ./rttys/html
1. npm install
1. npm run serve
1. open browse - console log
```
Uncaught ReferenceError: exports is not defined
    at Module.2bcc (overlay.js:4)
    at i (bootstrap:78)
    at Object.<anonymous> (App.vue?4241:1)
    at Object.281a (Rtty.vue:203)
    at i (bootstrap:78)
    at Module.56d7 (Rtty.vue?7e27:2)
    at i (bootstrap:78)
    at Object.0 (bootstrap:151)
    at i (bootstrap:78)
    at n (bootstrap:45)
```

```
$ npm --version
6.4.1

$ node --version
v10.15.3
```

**Comment by sgaynetdinov** [comment]
`npm run serve` work if delete line https://github.com/zhaojh329/rttys/blob/fff504193a5c9a4078da15394ab84dc788d47376/html/src/overlay.js#L4

**Comment by zhaojh329** [comment]
There is no problem running my local. Why?

**Comment by zhaojh329** [comment]
Have you run npm install first?

**Comment by sgaynetdinov** [comment]
> Have you run npm install first?

Yes, I first `npm install`

**Comment by sgaynetdinov** [comment]
My `package-lock.json`
[package-lock.txt](https://github.com/zhaojh329/rttys/files/2987821/package-lock.txt)

**Comment by zhaojh329** [comment]
OK. Can you make a PR to fix it?

**Comment by sgaynetdinov** [comment]
OK

**Comment by zhaojh329** [comment]
Can you make a PR to fix it?
