### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by nicovv44** [zhaojh329/rttys#19]
Not important but still...
![TranslationMissing](https://user-images.githubusercontent.com/26766888/60317853-237bf500-99b4-11e9-8b0e-921b3e2a43d3.png)

**Comment by zhaojh329** [comment]
The language is automatically recognized according to your browser configuration.

**Comment by nicovv44** [comment]
Hum.... I don't see any asian language in my connfiguration so I don't expect to see another language...
I thought maybe you missed that bit of translation.
![ChromeLangConfig](https://user-images.githubusercontent.com/26766888/60319580-31347900-99ba-11e9-95b9-f0349e33015c.png)
PS: thank you very much for your amazing work!

**Comment by zhaojh329** [comment]
Oh, I known. "暂无数据" not translated.

**Comment by zhaojh329** [comment]
Fixed.

https://github.com/zhaojh329/rttys/releases/tag/v2.10.3
