### ISSUE TITLE
登陆终端后tmux命令无法使用

### ISSUE THREAD

**Issue by lazyxwq** [zhaojh329/rttys#24]
嗨，我发现一个问题，如果在rttys中登陆了终端，如果使用tmux命令，会报错无法打开tmux terminal。
报错如下：
root@workstation:~$ tmux 
open terminal failed: missing or unsuitable terminal: unknown

请问下可以修复支持tmux命令么？

**Comment by zhaojh329** [comment]
没有使用过tmux

**Comment by hexiong0802** [comment]
升级一下tmux到最新版本就ok了
