### ISSUE TITLE
clear不能清屏

### ISSUE THREAD

**Issue by litongjava** [zhaojh329/rttys#29]
clear不能清屏
![image](https://user-images.githubusercontent.com/31761981/64662999-e5ec1b80-d47c-11e9-82a5-599915f1d026.png)

**Comment by zhaojh329** [comment]
我的环境是可以清屏的

**Comment by litongjava** [comment]
应该是操作系统的差异性,使用的操作系统是CentOS-7

**Comment by litongjava** [comment]
@zhaojh329 我的服务器是CentOS-7,作者能不能在CentOS-7尝试解决下这个问题

**Comment by zhaojh329** [comment]
好的
