### ISSUE TITLE
命令可以执行，设备无法连接

### ISSUE THREAD

**Issue by liangjiahuiLJH** [zhaojh329/rttys#35]
![命令1](https://user-images.githubusercontent.com/49118818/69635134-b4075000-108e-11ea-86dc-371d1d502b35.png)
![命令2](https://user-images.githubusercontent.com/49118818/69635142-b79ad700-108e-11ea-842e-3c33244871fb.png)
![登陆失败](https://user-images.githubusercontent.com/49118818/69635441-5a535580-108f-11ea-9500-36c7cb547f8b.png)
连接的账号密码是什么，我输的是客户端的用户名和密码，连接失败，但是命令的校验是正确的，客户端的用户名和密码正确才能执行

**Comment by zhaojh329** [comment]
应该是客户端限制了

**Comment by liangjiahuiLJH** [comment]
限制了什么，你说个关键字，我明天研究一下。------------------ 原始邮件 ------------------
发件人: "Jianhui Zhao"<notifications@github.com>
发送时间: 2019年11月26日(星期二) 晚上11:33
收件人: "zhaojh329/rttys"<rttys@noreply.github.com>;
抄送: "liangjiahuiLJH"<765291632@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhaojh329/rttys] 命令可以执行，设备无法连接 (#35)



应该是客户端限制了
 
&mdash;

**Comment by zhaojh329** [comment]
页面点击连接后，会在客户端运行/bin/login，你直接在客户端运行/bin/login登录试下

**Comment by liangjiahuiLJH** [comment]
![image](https://user-images.githubusercontent.com/49118818/69688188-472c9e00-1100-11ea-9afe-a26c110ae50d.png)
![image](https://user-images.githubusercontent.com/49118818/69688337-bbffd800-1100-11ea-8ce7-ca97bea74b8c.png)
root和ugw登陆都会直接提示login incorrect，liang可以登录成功

**Comment by liangjiahuiLJH** [comment]
已解决，与程序无关，隐藏/etc/securetty文件，或者在文件中增加几行pts/0,pts/1,...,pts/n
