### ISSUE TITLE
浏览器不能登录

### ISSUE THREAD

**Issue by yanghappyfrog** [zhaojh329/rttys#36]
服务端安装完成后，能正常启动：
pavt@pavt-server:~/tools/rttys-linux-amd64$ sudo ./rttys 
[sudo] pavt 的密码： 
INFO[0000] Go Version: go1.12.4                         
INFO[0000] Go OS/Arch: linux/amd64                      
INFO[0000] Rttys Version: 2.10.3                        
INFO[0000] Git Commit: 27abde3                          
INFO[0000] Build Time: 2019-08-13T11:26:31+0800         
INFO[0000] Listen on: :5912 SSL on                      
INFO[0021] New device:star-test                         
INFO[0043] Died device:star-test

   
浏览器输入服务器ip后出现下面提示：
Client sent an HTTP request to an HTTPS server.
没有设备列表。

**Comment by zhaojh329** [comment]
https://

**Comment by yanghappyfrog** [comment]
thanks!
