### ISSUE TITLE
修改vue不生效

### ISSUE THREAD

**Issue by gaoxf323** [zhaojh329/rttys#37]
您好，有个问题请教一下：
       我修改html/src/view下的vue文件后，执行./build.sh编译后对vue文件的修改并没有生效。后来发现将html删除掉后竟然也能编译。直接html下npm run build生成html文件，但是感觉好像和./build.sh编译没什么关系。
       请教下我想修改vue界面文件，如何编译才能使得这个生效呢？
非常感谢！

**Comment by zhaojh329** [comment]
github.com/rakyll/statik
参考

**Comment by gaoxf323** [comment]
好的，非常感谢您
