### ISSUE TITLE
是否实现客户端和服务端在一段时间内没有数据通讯就自动断开连接？

### ISSUE THREAD

**Issue by junlinChan** [zhaojh329/rttys#40]
您好！请问是否有实现客户端和服务端在一段时间内没有数据通讯就自动断开连接？

**Comment by zhaojh329** [comment]
那什么时候重写连接?

**Comment by junlinChan** [comment]
当我需要重新连接时通过tr069给设备下发任务，设备拿到任务后就重新启动rtty客户端与服务端建立起连接。就是在需要用时建立连接，不用时断开。

**Comment by zhaojh329** [comment]
那你自己决定什么时候启动rtty，什么时候kill rtty就可以了啊。
