### ISSUE TITLE
V3.1.3版本经常崩溃

### ISSUE THREAD

**Issue by Torchwoods** [zhaojh329/rttys#45]
V3.1.3版本每天都得手动启动一次，崩溃了

**Comment by jamespatriot** [comment]
经常panic: runtime error: makeslice: len out of range，有没有解决呀？

**Comment by zhaojh329** [comment]
> 经常panic: runtime error: makeslice: len out of range，有没有解决呀？

我自己的环境测试OK，能否提供你的环境，我好调试。
