### ISSUE TITLE
我使用的版本是，rttys-windows-amd64 v3.1.3 在阿里的windows server 2019运行，程序会自动关闭

### ISSUE THREAD

**Issue by zesongHuang** [zhaojh329/rttys#48]
您好：
比如 我今天早上运行 exe文件，但是第二天就会发现 cmd窗口关闭了，这是因为程序崩溃了吗？ 还是因为长时间没有终端连接，exe的程序自动关闭了？ 这种情况如何解决呢？  感谢回答~

**Comment by zhaojh329** [comment]
可能程序崩溃了。程序不会自动关闭。
