### ISSUE TITLE
能否加个断开连接的按钮

### ISSUE THREAD

**Issue by liyongming1982** [zhaojh329/rttys#5]
有的时候节点连接上来了，调试结束后，为了安全，想主动关闭与节点的整个连接
谢谢！

**Comment by zhaojh329** [comment]
断开后，怎么再开呢？

**Comment by liyongming1982** [comment]
断开后，节点自己主动连接就再有新的

**Comment by fuqiyang11** [comment]
给大神点赞了

**Comment by fuqiyang11** [comment]
还有，rtty中的mac带有冒号，就有问题，这个我自己做了修改了。。。

**Comment by fuqiyang11** [comment]
bool valid_id(const char *id)
111 {
112     while (*id) {
113         if (!isalnum(*id) && *id != '-' && *id != '_' && *id != ":")
114             return false;
115         id++;
116     }
117 
118     return true;
119 }

**Comment by fuqiyang11** [comment]
bool valid_id(const char *id)
{
    // while (*id) {
    //     if (!isalnum(*id) && *id != '-' && *id != '_')
    //         return false;
    //     id++;
    // }

    return true;
}
