### ISSUE TITLE
rttys crash with makeslice failed

### ISSUE THREAD

**Issue by tonyho** [zhaojh329/rttys#51]
### OS infor
Ubuntu 18.04 X64

### Rttys info
rttys is download in release page as 3.13 version.

Rttys startup information:
2020-07-20T17:30:19+08:00 |INFO| main.go:79 |Go Version: go1.14
2020-07-20T17:30:19+08:00 |INFO| main.go:80 |Go OS/Arch: linux/amd64
2020-07-20T17:30:19+08:00 |INFO| main.go:82 |Rttys Version: 3.1.3
2020-07-20T17:30:19+08:00 |INFO| main.go:88 |Git Commit: a065f65

## Crash
Details log:
```
[GIN] 2020/07/20 - 16:54:41 | 200 |      42.335µs |  180.166.64.115 | GET      /devs

panic: runtime error: makeslice: len out of range
goroutine 62 [running]:
main.(*Device).readLoop(0xc000176090)
        /home/zjh/go/src/github.com/zhaojh329/rttys/device.go:196 +0x49e
created by main.listenDevice
        /home/zjh/go/src/github.com/zhaojh329/rttys/device.go:256 +0x3be
root@VM-0-3-ubuntu:~/SW/rttys-linux-amd64#

```

**Comment by tonyho** [comment]
This happen day to day, only one device is connected.

**Comment by zhaojh329** [comment]
Does this happen when transferring files? The log shows that it happened when the file is transferring.
