### ISSUE TITLE
运行时常均显示为0

### ISSUE THREAD

**Issue by zsy-cn** [zhaojh329/rttys#73]
## 描述
运行时常均显示为0

## 运行环境
- 服务端程序 v3.5.0
- 客户端程序 v7.1.4 与 v7.4.0
- 服务端操作系统 Linux ecs 4.4.0-151-generic #178-Ubuntu x86_64 GNU/Linux
- 客户端操作系统 openwrt 14.07

## 截图
<img width="1656" alt="aa" src="https://user-images.githubusercontent.com/30883594/109141987-49fdbf00-7799-11eb-9102-71e779da380b.png">

**Comment by zhaojh329** [comment]
请确定你的客户端是 7.4.0.

![image](https://user-images.githubusercontent.com/28673295/109153079-58eb6e00-77a7-11eb-8c8a-76909529b85c.png)

**Comment by zsy-cn** [comment]
应该是版本不匹配的问题，客户端是 v7.1.2和v7.1.4。
另外使用v7.1.2客户端，使用v3.5.0服务端，设备连接不稳定，每隔几十秒就显示连接关闭。
有没有办法让客户端自动更新到最新版本，客户端变多之后手动更新很麻烦，谢谢！
