### ISSUE TITLE
请问编译后运行出现fatal error: runtime: out of memory怎么解决啊？

### ISSUE THREAD

**Issue by BigHero47** [zhaojh329/rttys#74]
编译后没报错，但是显示不了网页的时候，后端提示
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x5f0361, 0x16)
        E:/Go/src/runtime/panic.go:1117 +0x54
runtime.sysMap(0x4024000000, 0x20000000, 0xa25d30)
        E:/Go/src/runtime/mem_linux.go:169 +0xbc
runtime.(*mheap).sysAlloc(0xa0cd20, 0x20000000, 0xffffdd0a6878, 0x35af0)
        E:/Go/src/runtime/malloc.go:729 +0x188
runtime.(*mheap).grow(0xa0cd20, 0x10000, 0x0)
        E:/Go/src/runtime/mheap.go:1346 +0x80
runtime.(*mheap).allocSpan(0xa0cd20, 0x10000, 0xffffdd0a0001, 0x6efac)
        E:/Go/src/runtime/mheap.go:1173 +0x670
runtime.(*mheap).allocManual(0xa0cd20, 0x10000, 0xffffdd0a6a01, 0xffffffff)
        E:/Go/src/runtime/mheap.go:943 +0x44
runtime.stackalloc(0x20000000, 0x4c8e1b, 0x4c8e1c)
        E:/Go/src/runtime/stack.go:399 +0x228
runtime.copystack(0x4000206d80, 0x20000000)
        E:/Go/src/runtime/stack.go:849 +0x58
runtime.newstack()
        E:/Go/src/runtime/stack.go:1078 +0x218

之前几个版本没出现过，编译之后能用

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/rttys/releases/tag/v3.5.0

试下这个， 看有没有问题。

**Comment by BigHero47** [comment]
还是不行，之前就是用的3.5.0
打印信息比正常运行时候少了两条
2021-03-02T09:40:44+08:00 |INFO| main.go:35 |Git Commit: 4babe35 
2021-03-02T09:40:44+08:00 |INFO| main.go:39 |Build Time: 2021-02-22T14:52:12+0000 

![捕获](https://user-images.githubusercontent.com/33592824/109584039-d7476780-7b3b-11eb-8328-acf6553d5e64.JPG)

**Comment by zhaojh329** [comment]
你用的是 arm 架构，我这没有设备测试。我用最新版本的 rttys-linux-amd64-3.5.0 测试了没有问题。

**Comment by BigHero47** [comment]
哦哦好吧，谢谢

**Comment by zsy-cn** [comment]
是树莓派 4B 版本吗？我有编译好的树莓派4B 可用的 arm64 版本的，arm64 不能使用 amd64 架构的。

**Comment by zsichen** [comment]
试试开启swap？

zsy <notifications@github.com> 于2021年3月4日周四 上午8:38写道：

**Comment by zsichen** [comment]
试试开启swap？
