### ISSUE TITLE
会话已满问题

### ISSUE THREAD

**Issue by zsy-cn** [zhaojh329/rttys#78]
### rtty
* arch:  mips
* os: tina(openwrt)
* version: 7.4

### rttys
* arch: x86
* os: centos7
* version: 3.5

## Description
![680264413](https://user-images.githubusercontent.com/30883594/115248188-0e102600-a15a-11eb-92b4-ce581b077c45.jpg)

设备端网络不稳定，网页端有时会掉线，等网页端在连接的时候就会报这个错误，是客户端必须重启才会终止会话还是等一段时间客户端发现服务端没有指令会自动终止会话

**Comment by zhaojh329** [comment]
请用最新版。
