### ISSUE TITLE
Why was Darwin/Mac support removed?

### ISSUE THREAD

**Issue by innerop** [zhaojh329/rttys#8]
I have a Mackbook and I want to run the server locally so I don't have to pay for a server in the cloud.My servers are local to my network as well as on other Internet accessible networks. 

Doesn't Go make it easy to produce different binaries for different platforms?

**Comment by zhaojh329** [comment]
If you're just doing a test, you can install the VMware-workstation to run ubuntu.

**Comment by innerop** [comment]
I see. Makes sense. Thank u.
