### ISSUE TITLE
how to prohibit sign up?

### ISSUE THREAD

**Issue by Lemon080910** [zhaojh329/rttys#92]
### rtty
* arch:
* os:
* version:

### rttys
* arch:
* os:
* version:

## Description

```
Formating code blocks by wrapping them with pairs of ```
```

**Comment by brennerm** [comment]
@zhaojh329 What is the solution to this question? My goal is to prohibit UI login completely and if everyone can simply create an account that's impossible to do.

**Comment by tr4nk0** [comment]
Did you get any solution for restricting the sign up?
